version: '3.1'

services:
    teamcity:
        image: jetbrains/teamcity-server:latest
        volumes:
            - C:/TeamCity/data/:/data/teamcity_server/datadir
            - C:/TeamCity/logs/:/opt/teamcity/logs
        ports:
            - 8111:8111
        restart: unless-stopped
    teamcity-agent:
        image: jetbrains/teamcity-agent-with-compose:latest
        build: ./agent
        environment:
            SERVER_URL: http://teamcity:8111
        volumes:
            - C:/TeamCity/agent:/var/run/docker.sock
        restart: unless-stopped

volumes:
    teamcity-server-datadir:
    teamcity-server-logs:
